services:
  prodDB:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - prodDB:/var/lib/postgresql/data

  app:
    depends_on:
      prodDB:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
      - BNET_CLIENT_ID=${BNET_CLIENT_ID}
      - BNET_CLIENT_SECRET=${BNET_CLIENT_SECRET}
      - BNET_GRANT_TYPE=${BNET_GRANT_TYPE}
      - BNET_TOKEN_URL=${BNET_TOKEN_URL}
    image: arnaudlyard/bot-discord

volumes:
  prodDB:
