services:
  discordprodDB:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - discordprodDB:/var/lib/postgresql/data
    networks:
      - prodNetwork

  server:
    depends_on:
      discordprodDB:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST:-discordprodDB}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-postgres}      
      - DB_PORT=${DB_PORT:-5432}
      - DISCORD_TOKEN=${DISCORD_TOKEN:-token}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID:-123456}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY:-123456}
      - BNET_CLIENT_ID=${BNET_CLIENT_ID:-123456}
      - BNET_CLIENT_SECRET=${BNET_CLIENT_SECRET:-123456}
      - BNET_GRANT_TYPE=${BNET_GRANT_TYPE:-test}
      - BNET_TOKEN_URL=${BNET_TOKEN_URL:-url}
    image: arnaudlyard/bot-discord
    networks:
      - prodNetwork

volumes:
  discordprodDB:

networks:
  prodNetwork:
  
